### ISSUE TITLE
Hangar Crashed Server

### ISSUE THREAD

**Issue by twistedgrim** [Casimir255/QuantumHangar#38]
Looks like the server crashed due to a hangar call here. Thanks for looking!

22:07:59.7266 [ERROR]  Hangar.AutoHangar: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at QuantumHangar.Utils.GridUtilities.BiggestGrid(IEnumerable`1 Grids, MyCubeGrid& BiggestGrid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 499
   at QuantumHangar.Utils.GridUtilities.IsPlayerIdCorrect(Int64 playerId, List`1 gridList) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 445
   at QuantumHangar.Utils.GridUtilities.<>c__DisplayClass16_0.<FindGridList>b__1(Group group) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 432
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at QuantumHangar.Utils.GridUtilities.FindGridList(Int64 playerId, Boolean includeConnectedGrids) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 416
   at QuantumHangar.AutoHangar.AutoHangarWorker() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\AutoHangar\Autohangar.cs:line 103
   at QuantumHangar.AutoHangar.RunAutoHangar() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\AutoHangar\Autohangar.cs:line 46
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at QuantumHangar.Utils.GridUtilities.BiggestGrid(IEnumerable`1 Grids, MyCubeGrid& BiggestGrid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 499
   at QuantumHangar.Utils.GridUtilities.IsPlayerIdCorrect(Int64 playerId, List`1 gridList) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 445
   at QuantumHangar.Utils.GridUtilities.<>c__DisplayClass16_0.<FindGridList>b__1(Group group) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 432
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at QuantumHangar.Utils.GridUtilities.BiggestGrid(IEnumerable`1 Grids, MyCubeGrid& BiggestGrid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 499
   at QuantumHangar.Utils.GridUtilities.IsPlayerIdCorrect(Int64 playerId, List`1 gridList) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 445
   at QuantumHangar.Utils.GridUtilities.<>c__DisplayClass16_0.<FindGridList>b__1(Group group) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 432
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at QuantumHangar.Utils.GridUtilities.FindGridList(Int64 playerId, Boolean includeConnectedGrids) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 416
   at QuantumHangar.AutoHangar.AutoHangarWorker() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\AutoHangar\Autohangar.cs:line 103
   at QuantumHangar.AutoHangar.RunAutoHangar() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\AutoHangar\Autohangar.cs:line 46
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Aggregate[TSource](IEnumerable`1 source, Func`3 func)
   at QuantumHangar.Utils.GridUtilities.BiggestGrid(IEnumerable`1 Grids, MyCubeGrid& BiggestGrid) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 499
   at QuantumHangar.Utils.GridUtilities.IsPlayerIdCorrect(Int64 playerId, List`1 gridList) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 445
   at QuantumHangar.Utils.GridUtilities.<>c__DisplayClass16_0.<FindGridList>b__1(Group group) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 432
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

**Comment by Casimir255** [comment]
Fixed in latest update
