### ISSUE TITLE
[Crash] QH crashed server during Autohangar operation

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#40]
Normal autohangar due to inactivity; server went down

```20:42:23.0891 [INFO]   Hangar.AutoHangar: Invoking AutoHangar!
20:42:23.0891 [WARN]   Hangar.AutoHangar: AutoHangar: Getting Players!
20:42:23.0891 [WARN]   Hangar.AutoHangar: AutoHangar: Total players to check:4258
20:42:23.1047 [INFO]   QuantumHangar.Serialization.GridSerializer: 2
20:42:23.1547 [WARN]   QuantumHangar.Serialization.GridSerializer: Saving grid @Q:\76561198034175469\[05] Phalanx#00.sbc
20:42:23.1703 [FATAL]  Initializer: System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at VRage.Game.Entity.MyGameLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 288
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at VRage.Game.Entity.MyGameLogic.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 288
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
20:42:23.1703 [INFO]   Initializer: Generating minidump at C:\Torch-Servers\SENDS05\Instance\Minidump.dmp
20:42:23.1703 [ERROR]  Initializer: Keen broke the minidump, sorry.
20:42:23.7224 [INFO]   Hangar.AutoHangar: [05] Phalanx#00 was sent to Hangar due to inactivity!
20:42:23.8474 [INFO]   QuantumHangar.Serialization.GridSerializer: 1```

**Comment by Casimir255** [comment]
Fantastic

**Comment by Casimir255** [comment]
Hopefully this has been fixed... if not: Keen:tm:
