### ISSUE TITLE
[Bug] - Server crash when we ran !hm save from discord

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#47]
We restored Brickstrosity than tried to !hm save it from discord console and the server instantly crashed with the below
https://i.imgur.com/yZQxC7s.png
```
05:14:46.9213 [INFO]   ALE_GridBackup.BackupCommands: Server restored backup from path: C:\Torch-Servers\TDRAC04\Instance\GridBackups\144115188075856188\Brickstrosity_108997553508478067\2021_05_26_21_51_00.sbc
05:14:46.9213 [INFO]   Nexus.Commands.RecievedDiscordCommands: Command restore finished!
05:14:47.7494 [WARN]   ServerNetwork.Sync.ProgressionSync: Progression Update!
05:14:51.3275 [INFO]   ServerNetwork.Sync.PlayerSync: Silvermade joined! SID: 76561198052869524 Identity: 144115188075856046 RealPlayer: True InitialPlayer: True 
05:14:51.3275 [INFO]   Nexus.Utilities.PlayerEventController: Silvermade successfully connected! Running First Connection Methods!
05:14:52.7338 [INFO]   ServerNetwork.Sync.PlayerSync: TestTestTest
05:14:52.7494 [INFO]   ServerNetwork.Sync.PlayerSync: Aussie Rev passed ValidationChecks! SteamID: 76561198003614231, PlayerID: 144115188075855982
05:14:58.7651 [INFO]   ServerNetwork.Sync.PlayerSync: TestTestTest
05:14:58.7807 [INFO]   ServerNetwork.Sync.PlayerSync: Ashbane passed ValidationChecks! SteamID: 76561198138013290, PlayerID: 144115188075855979
05:15:00.0307 [INFO]   Concealment: 487/732 grids are concealed (66.53 %), 5 new.
05:15:02.5463 [INFO]   Nexus.Commands.RecievedDiscordCommands: Command save finished!
05:15:02.5463 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Utils.GridUtilities.FindGridList(String gridNameOrEntityId, MyCharacter character, List`1& Grids) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 270
   at QuantumHangar.GridResult.GetGrids(Chat Response, MyCharacter character, String GridNameOREntityID) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\SerializableData.cs:line 492
   at QuantumHangar.HangarChecks.AdminChecks.SaveGrid(String NameOrIdentity) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\HangarChecks\AdminChecks.cs:line 63
   at QuantumHangar.Commands.HangarSimpAdminCommands.<>c__DisplayClass0_0.<SaveGrid>b__0() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarAdminCommands.cs:line 86
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuantumHangar.Commands.HangarCommandSystem.<RunAdminTaskAsync>d__6.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommandSystem.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuantumHangar.Commands.HangarSimpAdminCommands.<SaveGrid>d__0.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarAdminCommands.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Utils.GridUtilities.FindGridList(String gridNameOrEntityId, MyCharacter character, List`1& Grids) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utils\GridUtilities.cs:line 270
   at QuantumHangar.GridResult.GetGrids(Chat Response, MyCharacter character, String GridNameOREntityID) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\SerializableData.cs:line 492
   at QuantumHangar.HangarChecks.AdminChecks.SaveGrid(String NameOrIdentity) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\HangarChecks\AdminChecks.cs:line 63
   at QuantumHangar.Commands.HangarSimpAdminCommands.<>c__DisplayClass0_0.<SaveGrid>b__0() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarAdminCommands.cs:line 86
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuantumHangar.Commands.HangarCommandSystem.<RunAdminTaskAsync>d__6.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommandSystem.cs:line 143
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuantumHangar.Commands.HangarSimpAdminCommands.<SaveGrid>d__0.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarAdminCommands.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
05:15:02.5463 [INFO]   Initializer: Generating minidump at C:\Torch-Servers\TDRAC04\Instance\Minidump.dmp
05:15:02.5463 [ERROR]  Initializer: Keen broke the minidump, sorry.
05:15:10.8901 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
05:15:10.9682 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
```

**Comment by Casimir255** [comment]
Fixed in latest commit
