### ISSUE TITLE
[Bug] Server fatal after player ran !h list

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#48]
Had someone run !h list; we got this fatal and the player started getting "your previous command hasn't finished" when trying to run !h list again.
The server definitely ...crashed...but until I went and clicked "ok" on the torch fatal alert; the server was.....running somehow still...which was like 15+minutes later that igot to it

```
06:22:25.6739 [INFO]   Nexus.Utilities.PlayerEventController: SindriLogged off! Clearing Data from NexusSystem!
06:22:25.6739 [INFO]   Nexus.Sync.PlayerDataSync: Saving Sindri meta data!
06:22:25.6739 [INFO]   Torch.Managers.MultiplayerManagerBase: Sindri (76561198137419151) Disconnected.
06:22:26.9239 [INFO]   Chat: Hangar (to [007...151]): You have 11/100 stored grids:
 [1] - Atmo Katana 2
 [2] - Atmo Katana 1
 [3] - Runner
 [4] - Projector Drag
 [5] - Tech Scrap
 [6] - The Jotunn
 [7] - Katana Drake
 [8] - Mini Hydro Refueler
 [9] - Jump stick
 [10] - Welder
 [11] - DCA Lawn Dart

06:22:26.9239 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Commands.HangarCommandSystem.RemoveCompletedTask(CommandContext Context) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommandSystem.cs:line 165
   at QuantumHangar.Commands.HangarCommandSystem.<RunTaskAsync>d__5.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommandSystem.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuantumHangar.Commands.HangarSimpCommands.<ListGrids>d__1.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommands.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantumHangar.Commands.HangarCommandSystem.RemoveCompletedTask(CommandContext Context) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommandSystem.cs:line 165
   at QuantumHangar.Commands.HangarCommandSystem.<RunTaskAsync>d__5.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommandSystem.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuantumHangar.Commands.HangarSimpCommands.<ListGrids>d__1.MoveNext() in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Commands\HangarCommands.cs:line 114
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
06:22:26.9239 [INFO]   Initializer: Generating minidump at C:\Torch-Servers\SENDS06\Instance\Minidump.dmp
06:22:26.9239 [ERROR]  Initializer: Keen broke the minidump, sorry.
06:22:31.2520 [INFO]   Nexus.Utilities.PlayerEventController: Player Sindri Joined! Requesting MetaData!
06:22:31.2520 [WARN]   Nexus.SeamlessClients.WorldRequestClass: Sending joinping to client!
06:22:31.2520 [INFO]   Torch.Server.Managers.MultiplayerManagerDedicated: Connection attempt by 76561198137419151 from 24.176.79.37
06:22:31.2520 [INFO]   Torch.Managers.MultiplayerManagerBase: Player Sindri joined (76561198137419151)
06:22:31.2989 [INFO]   StaticMarker.MarkerPlugin: Connected
06:22:31.2989 [INFO]   Essentials.RanksAndPermissionsModule: Binding ranks to Sindri's session (Expires when server restarts)
06:22:31.2989 [INFO]   Essentials.RanksAndPermissionsModule: The following ranks have been assiged to Sindri: Default
06:22:31.4708 [INFO]   ALE_DeathLocationFix.MySessionPatch: Stripped LastDeathPositions from world for client connect.
06:22:35.6583 [INFO]   ServerNetwork.Sync.PlayerSync: Lochemel passed ValidationChecks! SteamID: 76561198137910863, PlayerID: 144115188075861537
06:22:52.5646 [INFO]   Nexus.Sync.PlayerDataSync: Saving Vilk meta data!
06:22:52.5646 [INFO]   Nexus.Sync.PlayerDataSync: Saving Niner meta data!
06:22:52.5646 [INFO]   Nexus.Sync.PlayerDataSync: Saving Orion meta data!
06:22:52.5646 [INFO]   Nexus.Sync.PlayerDataSync: Saving JeffMan meta data!
06:22:53.0021 [INFO]   Nexus.Sync.ServerStartMessage: Original Sanbox Size: 73026kb  Compressed: 2358kb
06:22:53.9709 [INFO]   ServerNetwork.Sync.PlayerSync: Kepler J passed ValidationChecks! SteamID: 76561198034507414, PlayerID: 144115188075858033
06:23:06.4240 [INFO]   RexFix.Patches.ClusterReorderPatch: Clusters reordering. Prevented 101804 reorder calls.
06:23:07.8928 [INFO]   Concealment: 227/255 grids are concealed (89.02 %), 3 new.
06:23:29.0335 [INFO]   ServerNetwork.Sync.PlayerSync: Sindri joined! SID: 76561198137419151 Identity: 144115188075856011 RealPlayer: True InitialPlayer: True 
06:23:29.0335 [INFO]   Nexus.Utilities.PlayerEventController: Sindri successfully connected! Running First Connection Methods!
06:23:32.8460 [INFO]   Concealment: Revealed 3 grids near players.
06:23:33.2210 [WARN]   Nexus.BoundarySystem.PlayerSectorTransport: Sindri has up-to-date seamless client version: 1.2.20
06:23:42.1116 [INFO]   GridSplitNameKeeper: Closing grid Static Grid 1405 after splitting from VSI Maui Constructor
06:23:49.7210 [INFO]   Chat:  (to Sindri): Your previous command has yet to finish!
06:23:49.7210 [INFO]   Torch.Commands.CommandManager: Player Sindri ran command '!h list'
06:24:04.0648 [INFO]   ServerNetwork.Sync.PlayerSync: Dino passed ValidationChecks! SteamID: 76561198300097771, PlayerID: 144115188075856895
06:24:06.4242 [INFO]   RexFix.Patches.ClusterReorderPatch: Clusters reordering. Prevented 178262 reorder calls.
06:24:14.2993 [INFO]   Chat:  (to Sindri): Your previous command has yet to finish!
06:24:14.2993 [INFO]   Torch.Commands.CommandManager: Player Sindri ran command '!h list'
06:24:37.2368 [INFO]   Chat:  (to Sindri): Your previous command has yet to finish!
06:24:37.2368 [INFO]   Torch.Commands.CommandManager: Player Sindri ran command '!h list'
06:25:01.1744 [INFO]   Chat:  (to Sindri): Your previous command has yet to finish!
06:25:01.1744 [INFO]   Torch.Commands.CommandManager: Player Sindri ran command '!h list'
06:25:06.4244 [INFO]   RexFix.Patches.ClusterReorderPatch: Clusters reordering. Prevented 90062 reorder calls.
06:25:26.7526 [INFO]   SigmaAF11: Ghosts: Finished command
06:25:39.4089 [INFO]   Nexus.Commands.RecievedDiscordCommands: Command uptime finished!
06:26:06.4246 [INFO]   RexFix.Patches.ClusterReorderPatch: Clusters reordering. Prevented 26537 reorder calls.
06:26:19.7684 [INFO]   ALE_Biggest_Grids_Broadcast.GridsBroadcastPlugin: Removing Biggest Grid GPS from all Players.
06:26:19.7684 [INFO]   Torch.Commands.CommandManager: Server ran command '!sendmixgps true true'
06:26:45.3467 [INFO]   ServerNetwork.Sync.PlayerSync: Dino passed ValidationChecks! SteamID: 76561198300097771, PlayerID: 144115188075856895
06:26:46.6279 [INFO]   Torch.Commands.CommandManager: Player Vilk ran command '!tags'
06:26:54.7842 [INFO]   ALE_GridBackup.GridBackupPlugin: Backup took 276036ms (1905ms CPU)
06:26:54.7842 [INFO]   ALE_GridBackup.Utilities: Start deleting backups older than 7 days were deleted.
06:26:55.0654 [INFO]   ALE_GridBackup.Utilities: Backups older than 7 days were deleted.
06:26:56.2998 [INFO]   Chat: [Global:0] JeffMan: i hope the next update they will make a canvas gun to trap disarm other players
06:27:00.7686 [INFO]   Chat:  (to Vilk): Are you sure you want to continue? Enter the command again within 30 seconds to confirm fixship on SEN - Eagle Mk3.
06:27:00.7686 [INFO]   Torch.Commands.CommandManager: Player Vilk ran command '!fixship'
06:27:01.6748 [WARN]   ALE_ShipFixer.ShipFixerPlugin: Player Vilk used ShipFixerPlugin on Grid SEN - Eagle Mk3 for cut & paste!
06:27:01.8311 [INFO]   Chat:  (to Vilk): Ship was fixed!
06:27:01.8311 [INFO]   ALE_ShipFixer.Commands: Cooldown for Player Vilk started!
06:27:01.8311 [INFO]   Torch.Commands.CommandManager: Player Vilk ran command '!fixship'
06:27:06.4248 [INFO]   RexFix.Patches.ClusterReorderPatch: Clusters reordering. Prevented 90490 reorder calls.
```

**Comment by Casimir255** [comment]
Should be fixed
